# Generated by Django 3.1.7 on 2021-03-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tags'),
        ),
    ]
