# Generated by Django 3.1.7 on 2021-03-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210308_1343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='products',
            new_name='product',
        ),
    ]
