# Generated by Django 3.1.7 on 2021-03-09 05:19

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False 


    dependencies = [
        ('accounts', '0006_auto_20210309_0517'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='product',
            new_name='products',
        ),
    ]
