# Generated by Django 3.1.7 on 2021-03-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210309_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='customeradmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
