# Generated by Django 3.1.7 on 2021-03-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210311_0716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userform',
        ),
    ]
