# Generated by Django 3.1.7 on 2021-03-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210311_0924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userform',
        ),
    ]
